package de.tum.in.www1.bamboo.server;

/**
 * The filename of the artifacts generated by Bamboo that are
 * supported by the static code analysis parser.
 */
public enum StaticCodeAnalysisArtifacts {
    SPOTBUGS("spotbugsXml.xml"),
    CHECKSTYLE("checkstyle-result.xml"),
    SWIFTLINT("swiftlint-result.xml"),
    PMD("pmd.xml"),
    PMD_CPD("cpd.xml");

    private final String artifactFilename;

    StaticCodeAnalysisArtifacts(String artifactFilename) {
        this.artifactFilename = artifactFilename;
    }

    public String getArtifactFilename() {
        return artifactFilename;
    }
}
