package de.tum.in.www1.bamboo.server;

/**
 * The filename of the artifacts generated by Bamboo that are
 * supported by the static code analysis parser.
 */
public enum StaticCodeAnalysisArtifacts {
    CHECKSTYLE,
    SPOTBUGS,
    PMD,
    PMD_CPD,
    SWIFTLINT
}
